//This file was generated by xfali/gobatis-cmd at
//2020-02-07 11:43:44.4189871 +0800 CST m=+0.073004201

package test_package

import "time"

type TestTable struct {
    //TableName gobatis.ModelName `test_table`
    Id int `xfield:"id"`
    Username string `xfield:"username"`
    Password string `xfield:"password"`
    Createtime time.Time `xfield:"createtime"`
}
