//This file was generated by xfali/gobatis-cmd at
//2020-02-20 15:03:12.9833677 +0800 CST m=+0.049373301

package test

import "time"

type TestTable struct {
    //TableName gobatis.ModelName `test_table`
    Id int `xfield:"id"`
    Username string `xfield:"username"`
    Password string `xfield:"password"`
    Createtime time.Time `xfield:"createtime"`
}
